"""extend_employees_with_personal_and_contract_info

Revision ID: 23abb42ee202
Revises: 1afe981df5c7
Create Date: 2026-05-01 15:12:53.170743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23abb42ee202'
down_revision = '1afe981df5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('civility', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contract_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('trial_period_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('index_grade', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hours_per_week', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hours_per_month', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('navigo_pass', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pas_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('pas_rate')
        batch_op.drop_column('navigo_pass')
        batch_op.drop_column('monthly_salary')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('hours_per_month')
        batch_op.drop_column('hours_per_week')
        batch_op.drop_column('index_grade')
        batch_op.drop_column('level')
        batch_op.drop_column('contract_duration')
        batch_op.drop_column('trial_period_end')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('city')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address')
        batch_op.drop_column('civility')
        batch_op.drop_column('nationality')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('birth_name')

    # ### end Alembic commands ###
