"""add operations modules

Revision ID: 59439b56b921
Revises: c4d7e8f9a1b2
Create Date: 2026-05-03 20:32:44.520230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59439b56b921'
down_revision = 'c4d7e8f9a1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'planned'"), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'completed', 'cancelled')", name='check_session_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'session_date', name='unique_course_session')
    )
    op.create_table('student_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), server_default=sa.text('20'), nullable=False),
    sa.Column('appreciation', sa.Text(), nullable=True),
    sa.CheckConstraint('max_score > 0', name='check_assessment_max_score'),
    sa.CheckConstraint('score >= 0', name='check_assessment_score'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'present'"), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('present', 'absent', 'late', 'excused')", name='check_attendance_status'),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='unique_student_attendance')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default=sa.text('20'), nullable=False))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_departments_name', ['name'])

    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals', sa.Text(), nullable=True))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_positions_title', ['title'])

    with op.batch_alter_table('salary_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_details', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('effective_date')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_positions_title', type_='unique')

    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.drop_column('goals')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_departments_name', type_='unique')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('capacity')
        batch_op.drop_column('room')

    op.drop_table('attendance_records')
    op.drop_table('student_assessments')
    op.drop_table('course_sessions')
    # ### end Alembic commands ###
