"""expand to full schema

Revision ID: 6345ab3cab32
Revises: e46934f5a3ff
Create Date: 2026-05-01 10:40:48.662228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6345ab3cab32'
down_revision = 'e46934f5a3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('social_security_number', sa.Text(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('social_security_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_foreign_key(
        'fk_departments_manager_id_employees',
        'departments',
        'employees',
        ['manager_id'],
        ['id'],
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Text(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('annual_salary', sa.Float(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('father_first_name', sa.Text(), nullable=True),
    sa.Column('father_last_name', sa.Text(), nullable=True),
    sa.Column('father_email', sa.Text(), nullable=True),
    sa.Column('father_phone', sa.Text(), nullable=True),
    sa.Column('mother_first_name', sa.Text(), nullable=True),
    sa.Column('mother_last_name', sa.Text(), nullable=True),
    sa.Column('mother_email', sa.Text(), nullable=True),
    sa.Column('mother_phone', sa.Text(), nullable=True),
    sa.Column('address_number', sa.Integer(), nullable=True),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('zip_code', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('lives_alone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('address_number >= 0', name='check_address_number'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('time_slot', sa.Text(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.CheckConstraint("day IN ('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche')", name='check_day'),
    sa.CheckConstraint("level IN ('PREPA', 'NIV1', 'NIV2', 'NIV3', 'NIV4', 'NIV5', 'NIV6', 'NIV7')", name='check_level'),
    sa.CheckConstraint("time_slot IN ('matin', 'après-midi')", name='check_time_slot'),
    sa.CheckConstraint('end_hour > start_hour', name='check_hours_order'),
    sa.CheckConstraint('end_hour BETWEEN 0 AND 23', name='check_end_hour'),
    sa.CheckConstraint('start_hour BETWEEN 0 AND 23', name='check_start_hour'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.CheckConstraint("method IN ('CB', 'ESP', 'CHQ')", name='check_payment_method'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'annulee', 'en_attente')", name='check_enrollment_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='unique_enrollment')
    )
    op.create_table('payments_n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.CheckConstraint("method IN ('CB', 'ESP', 'CHQ')", name='check_payment_n_method'),
    sa.CheckConstraint('installment_number BETWEEN 1 AND 6', name='check_installment_number'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'installment_number', name='unique_installment_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_departments_manager_id_employees', 'departments', type_='foreignkey')
    op.drop_table('payments_n')
    op.drop_table('enrollments')
    op.drop_table('payments')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('salary_details')
    op.drop_table('performance_reviews')
    op.drop_table('employee_leave_requests')
    op.drop_table('sites')
    op.drop_table('employees')
    op.drop_table('departments')
    op.drop_table('positions')
    # ### end Alembic commands ###
